// Script: a Lua chunk that is either baked into the binary as bytes, or read
// from disk at runtime -- the two things luakit_embed_dir's generated table
// can hand back, without the host caring which. Not always embedded: a Debug
// build typically reads from disk instead, hence the plain name.

#pragma once

#include "luakit/core/api.hpp"
#include "luakit/error.hpp"

#include <cstddef>
#include <string>
#include <string_view>

namespace luakit {

// Exactly one of data/path is set: data for an embedded chunk (bytecode or
// source; loadbuffer sniffs which), path to load from disk. chunkname is
// only used in the data case -- loadfile already names the chunk after path.
struct Script {
  const char *chunkname;
  const unsigned char *data = nullptr;
  std::size_t len = 0;
  const char *path = nullptr;
};

struct NamedScript {
  std::string_view path;
  Script script;
};

// Linear search over a table generated by luakit_embed_dir -- small, and run
// only at startup. A missing entry is a build configuration bug (the path
// asked for was never registered), not something to recover from, hence
// Error rather than an optional return.
template <std::size_t N>
auto find_script(const NamedScript (&table)[N], std::string_view path) -> Script {
  for (const auto &entry : table) {
    if (entry.path == path) return entry.script;
  }
  throw Error("luakit: no script for '" + std::string(path) + "'");
}

// Loads and calls a script, leaving its one return value on the stack -- the
// shape a preloaded module opener needs (see Interpreter::preload). Meant as
// the body of a core::CFunction, so failure is reported through
// core::error(L) rather than thrown: this runs inside a raw Lua callback,
// and a C++ exception must not cross that frame.
inline auto load_script_as_module(core::State *L, const Script &s) -> int {
  const int status = s.data ? core::aux::loadbuffer(L, reinterpret_cast<const char *>(s.data),
                                                    static_cast<std::size_t>(s.len), s.chunkname)
                            : core::aux::loadfile(L, s.path);
  if (status != core::OK) return core::error(L);

  core::call(L, 0, 1);
  return 1;
}

}  // namespace luakit
