---@meta luna

-- Generated by luakit from the C++ registration. Do not edit.

---@class luna_module
local luna = {}

---@param a1 number
---@param a2 number
---@return number
function luna.sum(a1, a2) end

---@param a1 string
---@return string
function luna.greet(a1) end

---@param a1 number[]
---@param a2 number
---@return number[]
function luna.scale(a1, a2) end

function luna.boom() end

return luna
