---@meta tracker

-- Generated by luakit from the C++ registration. Do not edit.

---@class luna.Tracker
local Tracker = {}

---@param a1 number
---@return luna.Tracker
function Tracker:add(a1) end

---@return number
function Tracker:mean() end

---@return number
function Tracker:max() end

---@return string
function Tracker:name() end

---@class tracker_module
local tracker = {}

---@param a1 string
---@return luna.Tracker
function tracker.new(a1) end

return tracker
