---@meta world

-- Generated by luakit from the C++ registration. Do not edit.

---@class world.Vec2
---@field x number
---@field y number
local Vec2 = {}

---@return number
function Vec2:length() end

---@overload fun(a1: number): world.Vec2
---@param a1 world.Vec2
---@return world.Vec2
function Vec2:plus(a1) end

---@class world.Entity
---@field name string  # read-only
---@field position world.Vec2
local Entity = {}

---@param a1 world.Vec2
---@return world.Entity
function Entity:move_by(a1) end

---@class world.Creature : world.Entity
---@field hp integer
---@field facing "north"|"south"|"east"|"west"
---@field alive boolean  # read-only
local Creature = {}

---@param a1 integer
---@return world.Creature
function Creature:damage(a1) end

---@class world_module
local world = {}

---@param a1 string
---@return world.Creature
function world.spawn(a1) end

---@param a1 string
---@return world.Creature
function world.find(a1) end

---@param a1 string
---@return world.Creature
function world.summon(a1) end

---@param a1 string
---@return boolean
function world.banish(a1) end

---@return table<string, integer>
function world.census() end

---@param a1 string[]
---@return integer[]
function world.spawn_many(a1) end

---@param a1 "north"|"south"|"east"|"west"
---@return "north"|"south"|"east"|"west"
function world.opposite(a1) end

---@type table<string, "north"|"south"|"east"|"west">
world.Facing = {}

---@param a1 table
function world.configure(a1) end

---@param a1 string
---@vararg any
---@return integer
function world.log(a1, ...) end

---@param a1 function
function world.on_tick(a1) end

---@param a1 integer
---@return integer
function world.wait(a1) end

---@overload fun(a1: world.Creature, a2: world.Creature): number
---@param a1 world.Vec2
---@param a2 world.Vec2
---@return number
function world.distance(a1, a2) end

---@overload fun(a1: number, a2: number): world.Vec2
---@return world.Vec2
function world.vec2() end

return world
