#include <cstdio>

#include "luakit/interpreter.hpp"

#include "packages/luna.hpp"
#include "packages/tracker.hpp"

#ifdef LUAKIT_EMBEDDED_INIT_LUA
#include "init_lua.h"  // generated by luakit_embed_script: init_lua[], init_lua_len
#endif

auto main(int argc, char **argv) -> int try {
  (void)argc;
  (void)argv;

  auto interpreter = luakit::Interpreter();

  interpreter.open_libs();
  interpreter.preload(mod::luna());
  interpreter.preload(mod::tracker());

#ifdef LUAKIT_EMBEDDED_INIT_LUA
  interpreter.script_bytecode(init_lua, init_lua_len, "@lua/init.lua");
#else
  interpreter.script_file(LUNA_SCRIPT_PATH);
#endif

  return 0;

} catch (const std::exception &e) {
  std::fprintf(stderr, "fatal: %s\n", e.what());
  return 1;
}
