// The demo host.
//
// The script sets everything up; the engine then does what an engine does --
// runs frames, drives a scripted task, destroys something a mod still has a
// handle to, and reloads a plugin. Each of those is a direction the binding
// has to work in, and none of them is the script calling C++.

#include <cstdio>

#include "luakit/callback.hpp"
#include "luakit/coroutine.hpp"
#include "luakit/interpreter.hpp"

#include "packages/luna.hpp"
#include "packages/tracker.hpp"
#include "packages/world.hpp"

#ifdef LUAKIT_EMBEDDED_INIT_LUA
#include "init_lua.h"  // generated by luakit_embed_script: init_lua[], init_lua_len
#endif

namespace {

auto banner(const char *what) -> void {
  std::printf("\n=== %s ===\n", what);
}

auto load_script(luakit::Interpreter &lua) -> void {
#ifdef LUAKIT_EMBEDDED_INIT_LUA
  lua.script_bytecode(init_lua, init_lua_len, "@lua/init.lua");
#else
  lua.script_file(LUNA_SCRIPT_PATH);
#endif
}

// The handlers the script registered with world.on_tick, fired from here.
auto run_frames(int count) -> void {
  banner("engine loop");
  std::printf("[C++] %d tick handler(s) registered\n", world::handler_count());
  for (int i = 0; i < count; ++i) world::tick(0.5);
}

// A coroutine the engine drives. The script suspends itself with world.wait,
// which is a C++ function, so the schedule belongs to the host.
auto run_scripted_task(luakit::Interpreter &lua) -> void {
  banner("scripted task");

  auto quest = luakit::Coroutine(lua, "quest");
  int turn = 0;
  while (auto turns = quest.resume<int>(turn)) {
    std::printf("[C++] the task asked to wait %d turn(s)\n", *turns);
    turn += *turns;
  }
  std::printf("[C++] the task finished after %d turn(s)\n", turn);
}

// The engine breaking its half of the borrowed deal. A mod holding the
// creature is told so on the next use rather than reading freed memory.
auto destroy_something_lua_holds(luakit::Interpreter &lua) -> void {
  banner("an object the engine takes back");
  std::printf("[C++] destroying 'goblin' while a script still holds it\n");
  world::destroy("goblin");
  lua.global<luakit::Function>("report_stale_handle").call<void>();
}

// A shared object outliving the engine's own reference.
auto release_shared(luakit::Interpreter &lua) -> void {
  banner("shared ownership");
  std::printf("[C++] dropping the engine's reference to the summoned creature\n");
  world::release_summoned();
  lua.script("collectgarbage('collect')");
  lua.global<luakit::Function>("report_summoned").call<void>();
}

// Reloading a plugin without restarting: the module is rebuilt from scratch,
// which is what lets a script be edited while the host keeps running.
auto reload_plugin(luakit::Interpreter &lua) -> void {
  banner("hot reload");
  std::printf("[C++] world has been opened %d time(s)\n", world::open_count());
  lua.reload("world");
  std::printf("[C++] after reload, %d time(s)\n", world::open_count());
  std::printf("[C++] the population survived it: %d\n", world::population());
}

// Runs world::shutdown when the scope ends. Declared after the Interpreter so
// it is destroyed before it, which is the ordering that matters: the package
// holds Functions, a Function holds a registry reference, and giving one back
// after lua_close would touch a freed state.
//
// An RAII guard rather than a call at the end of main, so an early return or a
// thrown exception cannot skip it.
struct WorldSession {
  ~WorldSession() { world::shutdown(); }
};

}  // namespace

auto main(int argc, char **argv) -> int try {
  (void)argc;
  (void)argv;

  auto interpreter = luakit::Interpreter();
  auto session = WorldSession();

  interpreter.open_libs();
  interpreter.preload(mod::luna());
  interpreter.preload(mod::tracker());
  interpreter.preload(mod::world());

  load_script(interpreter);

  run_frames(3);
  run_scripted_task(interpreter);
  destroy_something_lua_holds(interpreter);
  release_shared(interpreter);
  reload_plugin(interpreter);

  return 0;

} catch (const std::exception &e) {
  std::fprintf(stderr, "fatal: %s\n", e.what());
  return 1;
}
