// The demo host.
//
// The script sets everything up; the engine then does what an engine does --
// runs frames, drives a scripted task, destroys something a mod still has a
// handle to, and reloads a plugin. Each of those is a direction the binding
// has to work in, and none of them is the script calling C++.

#include <cstddef>
#include <cstdio>

#include "luakit/callback.hpp"
#include "luakit/coroutine.hpp"
#include "luakit/interpreter.hpp"

#include "packages/luna.hpp"
#include "packages/tracker.hpp"
#include "packages/world/world.hpp"

#ifdef LUAKIT_EMBEDDED_INIT_LUA
// Generated by luakit_embed_script: init_lua[], init_lua_len, and the same
// pair for the examples module.
#include "examples_lua.h"
#include "init_lua.h"
#endif

namespace core = luakit::core;

namespace {

auto banner(const char *what) -> void {
  std::printf("\n=== %s ===\n", what);
}

auto open_examples(core::State *L) -> int {
#ifdef LUAKIT_EMBEDDED_EXAMPLES_LUA
  const int status = core::aux::loadbuffer(L, reinterpret_cast<const char *>(examples_lua),
                                           static_cast<std::size_t>(examples_lua_len), "@lua/examples.lua");
#else
  const int status = core::aux::loadfile(L, LUNA_EXAMPLES_PATH);
#endif

  if (status != core::OK) return core::error(L);

  core::call(L, 0, 1);
  return 1;
}

auto load_script(luakit::Interpreter &lua) -> void {
#ifdef LUAKIT_EMBEDDED_INIT_LUA
  lua.script_bytecode(init_lua, init_lua_len, "@lua/init.lua");
#else
  lua.script_file(LUNA_SCRIPT_PATH);
#endif
}

auto run_frames(int count) -> void {
  banner("engine loop");
  std::printf("[C++] %d tick handler(s) registered\n", world::handler_count());
  for (int i = 0; i < count; ++i) world::tick(0.5);
}

auto run_scripted_task(luakit::Interpreter &lua) -> void {
  banner("scripted task");

  auto quest = luakit::Coroutine(lua, "quest");
  int turn = 0;
  while (auto turns = quest.resume<int>(turn)) {
    std::printf("[C++] the task asked to wait %d turn(s)\n", *turns);
    turn += *turns;
  }
  std::printf("[C++] the task finished after %d turn(s)\n", turn);
}

auto destroy_something_lua_holds(luakit::Interpreter &lua) -> void {
  banner("an object the engine takes back");
  std::printf("[C++] destroying 'goblin' while a script still holds it\n");
  world::destroy("goblin");
  lua.global<luakit::Function>("report_stale_handle").call<void>();
}

auto release_shared(luakit::Interpreter &lua) -> void {
  banner("shared ownership");
  std::printf("[C++] dropping the engine's reference to the summoned creature\n");
  world::release_summoned();
  lua.script("collectgarbage('collect')");
  lua.global<luakit::Function>("report_summoned").call<void>();
}

auto reload_plugin(luakit::Interpreter &lua) -> void {
  banner("hot reload");

  std::printf("[C++] world has been opened %d time(s)\n", world::open_count());

  lua.reload("world");

  std::printf("[C++] after reload, %d time(s)\n", world::open_count());
  std::printf("[C++] the population survived it: %d\n", world::population());
}

struct WorldSession {
  ~WorldSession() { world::shutdown(); }
};

}  // namespace

auto main(int argc, char **argv) -> int try {
  (void)argc;
  (void)argv;

  auto interpreter = luakit::Interpreter();
  auto session = WorldSession();

  interpreter.open_libs();
  interpreter.preload(mod::luna()).preload(mod::tracker()).preload(mod::world());
  interpreter.preload({"examples", open_examples});

  load_script(interpreter);

  run_frames(3);
  run_scripted_task(interpreter);
  destroy_something_lua_holds(interpreter);
  release_shared(interpreter);
  reload_plugin(interpreter);

  return 0;

} catch (const std::exception &e) {
  std::fprintf(stderr, "fatal: %s\n", e.what());
  return 1;
}
