// GENERATED by tools/gen_api.py -- do not edit.
// Mechanical aliases for the Lua 5.4 C API. Macros live in api.hpp.

#pragma once

#include <lua.hpp>

static_assert(LUA_VERSION_NUM == 504, "luakit targets Lua 5.4");

namespace luakit::core {

// ---- types ----
using Alloc = ::lua_Alloc;
using CFunction = ::lua_CFunction;
using Debug = ::lua_Debug;
using Hook = ::lua_Hook;
using Integer = ::lua_Integer;
using KContext = ::lua_KContext;
using KFunction = ::lua_KFunction;
using Number = ::lua_Number;
using Reader = ::lua_Reader;
using State = ::lua_State;
using Unsigned = ::lua_Unsigned;
using WarnFunction = ::lua_WarnFunction;
using Writer = ::lua_Writer;

// ---- constants ----
inline constexpr auto NUMSIZES = LUAL_NUMSIZES;
inline constexpr auto AUTHORS = LUA_AUTHORS;
inline constexpr auto COLIBNAME = LUA_COLIBNAME;
inline constexpr auto COPYRIGHT = LUA_COPYRIGHT;
inline constexpr auto DBLIBNAME = LUA_DBLIBNAME;
inline constexpr auto ERRERR = LUA_ERRERR;
inline constexpr auto ERRFILE = LUA_ERRFILE;
inline constexpr auto ERRMEM = LUA_ERRMEM;
inline constexpr auto ERRRUN = LUA_ERRRUN;
inline constexpr auto ERRSYNTAX = LUA_ERRSYNTAX;
inline constexpr auto FILEHANDLE = LUA_FILEHANDLE;
inline constexpr auto GCCOLLECT = LUA_GCCOLLECT;
inline constexpr auto GCCOUNT = LUA_GCCOUNT;
inline constexpr auto GCCOUNTB = LUA_GCCOUNTB;
inline constexpr auto GCGEN = LUA_GCGEN;
inline constexpr auto GCINC = LUA_GCINC;
inline constexpr auto GCISRUNNING = LUA_GCISRUNNING;
inline constexpr auto GCRESTART = LUA_GCRESTART;
inline constexpr auto GCSETPAUSE = LUA_GCSETPAUSE;
inline constexpr auto GCSETSTEPMUL = LUA_GCSETSTEPMUL;
inline constexpr auto GCSTEP = LUA_GCSTEP;
inline constexpr auto GCSTOP = LUA_GCSTOP;
inline constexpr auto GNAME = LUA_GNAME;
inline constexpr auto HOOKCALL = LUA_HOOKCALL;
inline constexpr auto HOOKCOUNT = LUA_HOOKCOUNT;
inline constexpr auto HOOKLINE = LUA_HOOKLINE;
inline constexpr auto HOOKRET = LUA_HOOKRET;
inline constexpr auto HOOKTAILCALL = LUA_HOOKTAILCALL;
inline constexpr auto IOLIBNAME = LUA_IOLIBNAME;
inline constexpr auto LOADED_TABLE = LUA_LOADED_TABLE;
inline constexpr auto LOADLIBNAME = LUA_LOADLIBNAME;
inline constexpr auto MASKCALL = LUA_MASKCALL;
inline constexpr auto MASKCOUNT = LUA_MASKCOUNT;
inline constexpr auto MASKLINE = LUA_MASKLINE;
inline constexpr auto MASKRET = LUA_MASKRET;
inline constexpr auto MATHLIBNAME = LUA_MATHLIBNAME;
inline constexpr auto MINSTACK = LUA_MINSTACK;
inline constexpr auto MULTRET = LUA_MULTRET;
inline constexpr auto NOREF = LUA_NOREF;
inline constexpr auto NUMTAGS = LUA_NUMTAGS;
inline constexpr auto NUMTYPES = LUA_NUMTYPES;
inline constexpr auto OK = LUA_OK;
inline constexpr auto OPADD = LUA_OPADD;
inline constexpr auto OPBAND = LUA_OPBAND;
inline constexpr auto OPBNOT = LUA_OPBNOT;
inline constexpr auto OPBOR = LUA_OPBOR;
inline constexpr auto OPBXOR = LUA_OPBXOR;
inline constexpr auto OPDIV = LUA_OPDIV;
inline constexpr auto OPEQ = LUA_OPEQ;
inline constexpr auto OPIDIV = LUA_OPIDIV;
inline constexpr auto OPLE = LUA_OPLE;
inline constexpr auto OPLT = LUA_OPLT;
inline constexpr auto OPMOD = LUA_OPMOD;
inline constexpr auto OPMUL = LUA_OPMUL;
inline constexpr auto OPPOW = LUA_OPPOW;
inline constexpr auto OPSHL = LUA_OPSHL;
inline constexpr auto OPSHR = LUA_OPSHR;
inline constexpr auto OPSUB = LUA_OPSUB;
inline constexpr auto OPUNM = LUA_OPUNM;
inline constexpr auto OSLIBNAME = LUA_OSLIBNAME;
inline constexpr auto PRELOAD_TABLE = LUA_PRELOAD_TABLE;
inline constexpr auto REFNIL = LUA_REFNIL;
inline constexpr auto REGISTRYINDEX = LUA_REGISTRYINDEX;
inline constexpr auto RELEASE = LUA_RELEASE;
inline constexpr auto RIDX_GLOBALS = LUA_RIDX_GLOBALS;
inline constexpr auto RIDX_LAST = LUA_RIDX_LAST;
inline constexpr auto RIDX_MAINTHREAD = LUA_RIDX_MAINTHREAD;
inline constexpr auto SIGNATURE = LUA_SIGNATURE;
inline constexpr auto STRLIBNAME = LUA_STRLIBNAME;
inline constexpr auto TABLIBNAME = LUA_TABLIBNAME;
inline constexpr auto TBOOLEAN = LUA_TBOOLEAN;
inline constexpr auto TFUNCTION = LUA_TFUNCTION;
inline constexpr auto TLIGHTUSERDATA = LUA_TLIGHTUSERDATA;
inline constexpr auto TNIL = LUA_TNIL;
inline constexpr auto TNONE = LUA_TNONE;
inline constexpr auto TNUMBER = LUA_TNUMBER;
inline constexpr auto TSTRING = LUA_TSTRING;
inline constexpr auto TTABLE = LUA_TTABLE;
inline constexpr auto TTHREAD = LUA_TTHREAD;
inline constexpr auto TUSERDATA = LUA_TUSERDATA;
inline constexpr auto UTF8LIBNAME = LUA_UTF8LIBNAME;
inline constexpr auto VERSION = LUA_VERSION;
inline constexpr auto VERSION_MAJOR = LUA_VERSION_MAJOR;
inline constexpr auto VERSION_MINOR = LUA_VERSION_MINOR;
inline constexpr auto VERSION_NUM = LUA_VERSION_NUM;
inline constexpr auto VERSION_RELEASE = LUA_VERSION_RELEASE;
inline constexpr auto VERSION_RELEASE_NUM = LUA_VERSION_RELEASE_NUM;
inline constexpr auto VERSUFFIX = LUA_VERSUFFIX;
inline constexpr auto YIELD = LUA_YIELD;

// ---- core API (lua_*) ----
inline constexpr auto absindex = &::lua_absindex;
inline constexpr auto arith = &::lua_arith;
inline constexpr auto atpanic = &::lua_atpanic;
inline constexpr auto callk = &::lua_callk;
inline constexpr auto checkstack = &::lua_checkstack;
inline constexpr auto close = &::lua_close;
inline constexpr auto closeslot = &::lua_closeslot;
inline constexpr auto closethread = &::lua_closethread;
inline constexpr auto compare = &::lua_compare;
inline constexpr auto concat = &::lua_concat;
inline constexpr auto copy = &::lua_copy;
inline constexpr auto createtable = &::lua_createtable;
inline constexpr auto dump = &::lua_dump;
inline constexpr auto error = &::lua_error;
inline constexpr auto gc = &::lua_gc;
inline constexpr auto getallocf = &::lua_getallocf;
inline constexpr auto getfield = &::lua_getfield;
inline constexpr auto getglobal = &::lua_getglobal;
inline constexpr auto gethook = &::lua_gethook;
inline constexpr auto gethookcount = &::lua_gethookcount;
inline constexpr auto gethookmask = &::lua_gethookmask;
inline constexpr auto geti = &::lua_geti;
inline constexpr auto getinfo = &::lua_getinfo;
inline constexpr auto getiuservalue = &::lua_getiuservalue;
inline constexpr auto getlocal = &::lua_getlocal;
inline constexpr auto getmetatable = &::lua_getmetatable;
inline constexpr auto getstack = &::lua_getstack;
inline constexpr auto gettable = &::lua_gettable;
inline constexpr auto gettop = &::lua_gettop;
inline constexpr auto getupvalue = &::lua_getupvalue;
inline constexpr auto iscfunction = &::lua_iscfunction;
inline constexpr auto isinteger = &::lua_isinteger;
inline constexpr auto isnumber = &::lua_isnumber;
inline constexpr auto isstring = &::lua_isstring;
inline constexpr auto isuserdata = &::lua_isuserdata;
inline constexpr auto isyieldable = &::lua_isyieldable;
inline constexpr auto len = &::lua_len;
inline constexpr auto load = &::lua_load;
inline constexpr auto newstate = &::lua_newstate;
inline constexpr auto newthread = &::lua_newthread;
inline constexpr auto newuserdatauv = &::lua_newuserdatauv;
inline constexpr auto next = &::lua_next;
inline constexpr auto pcallk = &::lua_pcallk;
inline constexpr auto pushboolean = &::lua_pushboolean;
inline constexpr auto pushcclosure = &::lua_pushcclosure;
inline constexpr auto pushfstring = &::lua_pushfstring;
inline constexpr auto pushinteger = &::lua_pushinteger;
inline constexpr auto pushlightuserdata = &::lua_pushlightuserdata;
inline constexpr auto pushlstring = &::lua_pushlstring;
inline constexpr auto pushnil = &::lua_pushnil;
inline constexpr auto pushnumber = &::lua_pushnumber;
inline constexpr auto pushstring = &::lua_pushstring;
inline constexpr auto pushthread = &::lua_pushthread;
inline constexpr auto pushvalue = &::lua_pushvalue;
inline constexpr auto pushvfstring = &::lua_pushvfstring;
inline constexpr auto rawequal = &::lua_rawequal;
inline constexpr auto rawget = &::lua_rawget;
inline constexpr auto rawgeti = &::lua_rawgeti;
inline constexpr auto rawgetp = &::lua_rawgetp;
inline constexpr auto rawlen = &::lua_rawlen;
inline constexpr auto rawset = &::lua_rawset;
inline constexpr auto rawseti = &::lua_rawseti;
inline constexpr auto rawsetp = &::lua_rawsetp;
inline constexpr auto resetthread = &::lua_resetthread;
inline constexpr auto resume = &::lua_resume;
inline constexpr auto rotate = &::lua_rotate;
inline constexpr auto setallocf = &::lua_setallocf;
inline constexpr auto setcstacklimit = &::lua_setcstacklimit;
inline constexpr auto setfield = &::lua_setfield;
inline constexpr auto setglobal = &::lua_setglobal;
inline constexpr auto sethook = &::lua_sethook;
inline constexpr auto seti = &::lua_seti;
inline constexpr auto setiuservalue = &::lua_setiuservalue;
inline constexpr auto setlocal = &::lua_setlocal;
inline constexpr auto setmetatable = &::lua_setmetatable;
inline constexpr auto settable = &::lua_settable;
inline constexpr auto settop = &::lua_settop;
inline constexpr auto setupvalue = &::lua_setupvalue;
inline constexpr auto setwarnf = &::lua_setwarnf;
inline constexpr auto status = &::lua_status;
inline constexpr auto stringtonumber = &::lua_stringtonumber;
inline constexpr auto toboolean = &::lua_toboolean;
inline constexpr auto tocfunction = &::lua_tocfunction;
inline constexpr auto toclose = &::lua_toclose;
inline constexpr auto tointegerx = &::lua_tointegerx;
inline constexpr auto tolstring = &::lua_tolstring;
inline constexpr auto tonumberx = &::lua_tonumberx;
inline constexpr auto topointer = &::lua_topointer;
inline constexpr auto tothread = &::lua_tothread;
inline constexpr auto touserdata = &::lua_touserdata;
inline constexpr auto type = &::lua_type;
inline constexpr auto typename_ = &::lua_typename;
inline constexpr auto upvalueid = &::lua_upvalueid;
inline constexpr auto upvaluejoin = &::lua_upvaluejoin;
inline constexpr auto version = &::lua_version;
inline constexpr auto warning = &::lua_warning;
inline constexpr auto xmove = &::lua_xmove;
inline constexpr auto yieldk = &::lua_yieldk;

namespace aux {

// ---- types ----
using Buffer = ::luaL_Buffer;
using Reg = ::luaL_Reg;
using Stream = ::luaL_Stream;

// ---- auxiliary library (luaL_*) ----
inline constexpr auto addgsub = &::luaL_addgsub;
inline constexpr auto addlstring = &::luaL_addlstring;
inline constexpr auto addstring = &::luaL_addstring;
inline constexpr auto addvalue = &::luaL_addvalue;
inline constexpr auto argerror = &::luaL_argerror;
inline constexpr auto buffinit = &::luaL_buffinit;
inline constexpr auto buffinitsize = &::luaL_buffinitsize;
inline constexpr auto callmeta = &::luaL_callmeta;
inline constexpr auto checkany = &::luaL_checkany;
inline constexpr auto checkinteger = &::luaL_checkinteger;
inline constexpr auto checklstring = &::luaL_checklstring;
inline constexpr auto checknumber = &::luaL_checknumber;
inline constexpr auto checkoption = &::luaL_checkoption;
inline constexpr auto checkstack = &::luaL_checkstack;
inline constexpr auto checktype = &::luaL_checktype;
inline constexpr auto checkudata = &::luaL_checkudata;
inline constexpr auto checkversion_ = &::luaL_checkversion_;
inline constexpr auto error = &::luaL_error;
inline constexpr auto execresult = &::luaL_execresult;
inline constexpr auto fileresult = &::luaL_fileresult;
inline constexpr auto getmetafield = &::luaL_getmetafield;
inline constexpr auto getsubtable = &::luaL_getsubtable;
inline constexpr auto gsub = &::luaL_gsub;
inline constexpr auto len = &::luaL_len;
inline constexpr auto loadbufferx = &::luaL_loadbufferx;
inline constexpr auto loadfilex = &::luaL_loadfilex;
inline constexpr auto loadstring = &::luaL_loadstring;
inline constexpr auto newmetatable = &::luaL_newmetatable;
inline constexpr auto newstate = &::luaL_newstate;
inline constexpr auto openlibs = &::luaL_openlibs;
inline constexpr auto optinteger = &::luaL_optinteger;
inline constexpr auto optlstring = &::luaL_optlstring;
inline constexpr auto optnumber = &::luaL_optnumber;
inline constexpr auto prepbuffsize = &::luaL_prepbuffsize;
inline constexpr auto pushresult = &::luaL_pushresult;
inline constexpr auto pushresultsize = &::luaL_pushresultsize;
inline constexpr auto ref = &::luaL_ref;
inline constexpr auto requiref = &::luaL_requiref;
inline constexpr auto setfuncs = &::luaL_setfuncs;
inline constexpr auto setmetatable = &::luaL_setmetatable;
inline constexpr auto testudata = &::luaL_testudata;
inline constexpr auto tolstring = &::luaL_tolstring;
inline constexpr auto traceback = &::luaL_traceback;
inline constexpr auto typeerror = &::luaL_typeerror;
inline constexpr auto unref = &::luaL_unref;
inline constexpr auto where = &::luaL_where;

}  // namespace aux

namespace lib {

// ---- standard library openers (luaopen_*) ----
inline constexpr auto base = &::luaopen_base;
inline constexpr auto coroutine = &::luaopen_coroutine;
inline constexpr auto debug = &::luaopen_debug;
inline constexpr auto io = &::luaopen_io;
inline constexpr auto math = &::luaopen_math;
inline constexpr auto os = &::luaopen_os;
inline constexpr auto package = &::luaopen_package;
inline constexpr auto string = &::luaopen_string;
inline constexpr auto table = &::luaopen_table;
inline constexpr auto utf8 = &::luaopen_utf8;

}  // namespace lib

}  // namespace luakit::core
